export const roboCommands = [
  {
    head: true,
    action: 'inclination',
    movement: 1,
    commands: [
      'Top',
      'Up',
      'Look up',
      'Look to top',
      'Head up',
      'Move your head up',
    ],
  },
  {
    head: true,
    action: 'inclination',
    movement: 2,
    commands: ['Rest', 'Rest your head'],
  },
  {
    head: true,
    action: 'inclination',
    movement: 3,
    commands: ['Down', 'Look down', 'Move your head down'],
  },
  {
    head: true,
    action: 'rotation',
    movement: 1,
    commands: [
      'Turn right',
      'Rotate your head to minus ninety',
      'Move your head to minus ninety',
      'Rotate your head to position one',
      'Move your head to position one',
    ],
  },
  {
    head: true,
    action: 'rotation',
    movement: 2,
    commands: [
      'Look right',
      'Rotate your head to minus forty five',
      'Move your head to minus forty five',
      'Rotate your head to position two',
      'Move your head to position two',
    ],
  },
  {
    head: true,
    action: 'rotation',
    movement: 3,
    commands: [
      'Look front',
      'Look to me',
      'Rotate your head to position three',
      'Move your head to position three',
    ],
  },
  {
    head: true,
    action: 'rotation',
    movement: 4,
    commands: [
      'Look left',
      'Rotate your head to forty five',
      'Move your head to forty five',
      'Rotate your head to position four',
      'Move your head to position four',
    ],
  },
  {
    head: true,
    action: 'rotation',
    movement: 5,
    commands: [
      'Turn left',
      'Rotate your head to ninety',
      'Move your head to ninety',
      'Rotate your head to position five',
      'Move your head to position five',
    ],
  },
  {
    arm: 'left',
    part: 'elbow',
    movement: 1,
    commands: [
      'Rest your left elbow',
      'Left elbow rest',
      'Elbow left rest',
      'Left elbow to position one',
      'Elbow left to position one',
      'Move your left elbow to position one',
    ],
  },
  {
    arm: 'left',
    part: 'elbow',
    movement: 2,
    commands: [
      'Contract slightly your left elbow',
      'Left elbow slightly contracted',
      'Elbow left slightly contracted',
      'Left elbow to position two',
      'Elbow left to position two',
      'Move your left elbow to position two',
    ],
  },
  {
    arm: 'left',
    part: 'elbow',
    movement: 3,
    commands: [
      'Contract your left elbow',
      'Left elbow contracted',
      'Elbow left contracted',
      'Left elbow to position three',
      'Elbow left to position three',
      'Move your left elbow to position three',
    ],
  },
  {
    arm: 'left',
    part: 'elbow',
    movement: 4,
    commands: [
      'Contract tightly your left elbow',
      'Left elbow tightly contracted',
      'Elbow left tightly contracted',
      'Left elbow to position four',
      'Elbow left to position four',
      'Move your left elbow to position four',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 1,
    commands: [
      'Rotate your left wrist to minus ninety',
      'Move your left wrist to minus ninety',
      'Rotate your left wrist to position one',
      'Move your left wrist to position one',
      'Left wrist to position one',
      'Wrist left to position one',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 2,
    commands: [
      'Rotate your left wrist to minus forty five',
      'Move your left wrist to minus forty five',
      'Rotate your left wrist to position two',
      'Move your left wrist to position two',
      'Left wrist to position two',
      'Wrist left to position two',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 3,
    commands: [
      'Rest your left wrist',
      'Left wrist rest',
      'Wrist left rest',
      'Rotate your left wrist to position three',
      'Move your left wrist to position three',
      'Left wrist to position three',
      'Wrist left to position three',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 4,
    commands: [
      'Rotate your left wrist to forty five',
      'Move your left wrist to forty five',
      'Rotate your left wrist to position four',
      'Move your left wrist to position four',
      'Left wrist to position four',
      'Wrist left to position four',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 5,
    commands: [
      'Rotate your left wrist to ninety',
      'Move your left wrist to ninety',
      'Rotate your left wrist to position five',
      'Move your left wrist to position five',
      'Left wrist to position five',
      'Wrist left to position five',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 6,
    commands: [
      'Rotate your left wrist to one hundred thirty five',
      'Move your left wrist to one hundred thirty five',
      'Rotate your left wrist to position six',
      'Move your left wrist to position six',
      'Left wrist to position six',
      'Wrist left to position six',
    ],
  },
  {
    arm: 'left',
    part: 'wrist',
    movement: 7,
    commands: [
      'Rotate your left wrist to one hundred eighty',
      'Move your left wrist to one hundred eighty',
      'Rotate your left wrist to position seven',
      'Move your left wrist to position seven',
      'Left wrist to position seven',
      'Wrist left to position seven',
    ],
  },
  {
    arm: 'right',
    part: 'elbow',
    movement: 1,
    commands: [
      'Rest your right elbow',
      'Right elbow rest',
      'Elbow right rest',
      'Right elbow to position one',
      'Elbow right to position one',
      'Move your right elbow to position one',
    ],
  },
  {
    arm: 'right',
    part: 'elbow',
    movement: 2,
    commands: [
      'Contract slightly your right elbow',
      'Right elbow slightly contracted',
      'Elbow right slightly contracted',
      'Right elbow to position two',
      'Elbow right to position two',
      'Move your right elbow to position two',
    ],
  },
  {
    arm: 'right',
    part: 'elbow',
    movement: 3,
    commands: [
      'Contract your right elbow',
      'Right elbow contracted',
      'Elbow right contracted',
      'Right elbow to position three',
      'Elbow right to position three',
      'Move your right elbow to position three',
    ],
  },
  {
    arm: 'right',
    part: 'elbow',
    movement: 4,
    commands: [
      'Contract tightly your right elbow',
      'Right elbow tightly contracted',
      'Elbow right tightly contracted',
      'Right elbow to position four',
      'Elbow right to position four',
      'Move your right elbow to position four',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 1,
    commands: [
      'Rotate your right wrist to minus ninety',
      'Move your right wrist to minus ninety',
      'Rotate your right wrist to position one',
      'Move your right wrist to position one',
      'Right wrist to position one',
      'Wrist right to position one',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 2,
    commands: [
      'Rotate your right wrist to minus forty five',
      'Move your right wrist to minus forty five',
      'Rotate your right wrist to position two',
      'Move your right wrist to position two',
      'Right wrist to position two',
      'Wrist right to position two',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 3,
    commands: [
      'Rest your right wrist',
      'Right wrist rest',
      'Wrist right rest',
      'Rotate your right wrist to position three',
      'Move your right wrist to position three',
      'Right wrist to position three',
      'Wrist right to position three',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 4,
    commands: [
      'Rotate your right wrist to forty five',
      'Move your right wrist to forty five',
      'Rotate your right wrist to position four',
      'Move your right wrist to position four',
      'Right wrist to position four',
      'Wrist right to position four',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 5,
    commands: [
      'Rotate your right wrist to ninety',
      'Move your right wrist to ninety',
      'Rotate your right wrist to position five',
      'Move your right wrist to position five',
      'Right wrist to position five',
      'Wrist right to position five',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 6,
    commands: [
      'Rotate your right wrist to one hundred thirty five',
      'Move your right wrist to one hundred thirty five',
      'Rotate your right wrist to position six',
      'Move your right wrist to position six',
      'Right wrist to position six',
      'Wrist right to position six',
    ],
  },
  {
    arm: 'right',
    part: 'wrist',
    movement: 7,
    commands: [
      'Rotate your right wrist to one hundred eighty',
      'Move your right wrist to one hundred eighty',
      'Rotate your right wrist to position seven',
      'Move your right wrist to position seven',
      'Right wrist to position seven',
      'Wrist right to position seven',
    ],
  },
];
